version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    ports:
      - :27017:27017"
    volumes:
      - mongodb-data:/data/db
  
  server:
    build:
      context: ./server/
      target: developement
    volumes:
    - .:/usr/src/app
    ports:
    - "3333:3333"
    environment:
     NODE_ENV: developement
     DB_URL: mongodb://mongo_db/testdb
     PORT: 3333
  
    depends_on:
      - mongo_db
  
  client:
    build: 
      context: ./client/
      target: developement
    ports:
      - "3000:3000"
    environment:
      - DB_URL=
volumes:
  mogodb-data:
  